apiVersion: v1
kind: Service
metadata:
  name: quarkus-demo
  namespace: admin-admin
spec:
  type: ClusterIP
  selector:
    app: quarkus-demo
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
